services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    networks:
      - main
    ports:
      - "5672:5672"
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build: .
    volumes:
      - .:/code
    container_name: celery_worker
    command: "celery -A rssreader worker -l INFO"
    depends_on:
      - app
      - rabbitmq
      - postgres
    image: celeryworker
    environment:
      - C_FORCE_ROOT="true"
    networks:
      - main
    restart: on-failure

  celery-beat:
    build: .
    volumes:
      - .:/code
    command: celery -A rssreader beat -l INFO 
    environment:
      - C_FORCE_ROOT="true"
  app:
    build: .
    command: sh -c "python manage.py migrate && gunicorn rssreader.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
    depends_on:
      - postgres
      - rabbitmq
    expose:
      - "8000"
    networks:
      - main
    restart: on-failure

  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    image: nginx:latest
    networks:
      - main
    ports:
      - "10080:80"
      - "10443:443"
    restart: on-failure
    volumes:
      - ./nginx.conf/conf/nginx.conf




networks:
  main:

volumes:
  postgres_data: